version: "3.9"

services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task_backend
    volumes:
      - ${PWD}:/apps
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    container_name: task_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - task_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nginx:
    image: nginx
    restart: always
    container_name: task_nginx
    ports:
      - "81:81"
    volumes:
      - ./task_nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  task_postgres_data:
